name: Angular CI/CD to GitHub Pages

on:
  push:
    branches:
      - master # Trigger on push to master branch

jobs:
  build:
    runs-on: windows-latest # The type of runner that the job will run on

    strategy:
      matrix:
        node-version: [11.6.0] # Node.js version for the runner

    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Dev
      run: npm run dev 
