name: Angular CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build -- --prod
    
    - name: Run tests
      run: npm test

    # Add more steps if you want to deploy or perform additional tasks
